# Generated by Django 3.0.5 on 2020-04-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address_1',
            new_name='street_address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address_2',
            new_name='street_address2',
        ),
    ]
